bes/1/allservices/AllServices/Models/RolesManagement/AllRolesModel.cs
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AllServices.Models.RolesManagement
{
    public class AllRolesModel
    {
        [Required(ErrorMessage = "Заполните поле 'Название роли'!")]
        [Display(Name = "Название роли")]
        public string Name { get; set; }
        public List<IdentityRole> Roles { get; set; }
    }
}

bes/1/allservices/AllServices/Controllers/RolesManagementController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AllServices.Models.RolesManagement;
using Microsoft.AspNetCore.Authorization;

namespace AllServices.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesManagementController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<UserManagementController> _logger;

        public RolesManagementController(RoleManager<IdentityRole> roleManager, ILogger<UserManagementController> logger)
        {
            _roleManager = roleManager;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            AllRolesModel model = new AllRolesModel() { Roles = _roleManager.Roles.ToList() };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (id != null)
            {
                var db_role = await _roleManager.FindByIdAsync(id);
                if (db_role != null)
                {
                    var result = await _roleManager.DeleteAsync(db_role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(AllRolesModel allRoles)
        {
            if (ModelState.IsValid)
            {
                var exist = await _roleManager.RoleExistsAsync(allRoles.Name);
                if (!exist)
                {
                    var result = await _roleManager.CreateAsync(new IdentityRole(allRoles.Name));
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Произошла ошибка при добавлении");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Роль уже существует");
                }
            }
            else
            {
                ModelState.AddModelError("", "Неверное имя роли");
            }
            allRoles.Roles = _roleManager.Roles.ToList();
            return View("Index", allRoles);
        }

    }
}

bes/1/allservices/AllServices/Views/RolesManagement/Index.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Identity
@model AllServices.Models.RolesManagement.AllRolesModel
@{
    ViewData["Title"] = "Управление ролями";
}

@await Html.PartialAsync("_allRoles", Model.Roles)

<div class="concat-block">
    <br />
    <div class="row">
        <div class="edit-block">
            <form asp-action="CreateRole" asp-controller="RolesManagement" asp-antiforgery="true" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" value=""  class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="buttons-panel">
                    <div class="buttons-panel-item">
                        <input type="submit" value="Создать" class="btn-1 btn-default" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

bes/1/allservices/AllServices/Views/RolesManagement/_allRoles.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Identity
@model List<IdentityRole>

<div class="concat-block">
    <h2 class="h2">Список ролей</h2>
    <hr />
    <div class="table-block">
        <div class="table-line">
            <div class="table-item">Роль</div>
            <div class="table-item">Действия</div>
        </div>
        @foreach (IdentityRole item in Model)
        {
            <div class="table-line">
                <div class="table-item">@item.Name</div>
                <div class="table-item">
                    <a asp-action="DeleteRole" asp-controller="RolesManagement" asp-route-id="@item.Id" onclick="return confirmDelete();">Удалить</a>
                </div>
            </div>
        }
    </div>
</div>