bes/1/allservices/AllServices/Models/OT/ViewModelAddExam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModelsLibrary.Models;
using System.ComponentModel.DataAnnotations;

namespace AllServices.Models.OT
{
    public class ViewModelAddExam
    {
       
        [Display(Name = "Сотрудник ")]
        public int IdPerson { get; set; }

        [Display(Name ="Протокол № ")]
        public int NumProtocol { get; set; }

        [Required(ErrorMessage = "Заполните поле!")]
        [Display(Name = "Дата проведения проверки ")]
        public DateTime DateProtocol { get; set; }

        [Display(Name ="Комиссия на основании приказа № ")]
        public Document Commission { get; set; }

        [Required(ErrorMessage = "Укажите причину проверки!")]
        [Display(Name = "Тип проверки ")]
        public ExaminationReason Reason { get; set; }

        [Required(ErrorMessage = "Выберите результат проверки!")]
        [Display(Name = "Результат проверки ")]
        public bool? Result { get; set; }

        [Required(ErrorMessage = "Заполните поле!")]
        [Display(Name = "Примечание ")]
        public string Notice { get; set; }


    }
}

bes/1/allservices/AllServices/Controllers/OTController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AllServices.Models;
using AllServices.Models.Examination;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ModelsLibrary;
using ModelsLibrary.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using AllServices.Models.OT;
using ModelsLibrary.Models.OT;

namespace AllServices.Controllers
{
    public class OTController : Controller
    {
        private static BesContext _db;
        private IHostingEnvironment _env;
        private readonly IEmailSender _emailSender;
        private static List<Examination> checkExaminations;
        private static CheckDate checkDate;

        public OTController(BesContext besContext, IHostingEnvironment env, IEmailSender emailSender)
        {
            _db = besContext;
            _env = env;
            _emailSender = emailSender;
        }

        [Authorize(Roles = "user")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "manager")]
        //Проверка знаний
        [HttpGet]
        public IActionResult AllExaminations(string message)
        {
            var exams = _db.Examinations.ToList();
            ViewBag.Message = message;
            return View(exams);
        }

        [Authorize(Roles = "manager")]
        [HttpGet]
        public IActionResult CheckExaminations()
        {
            checkDate = new CheckDate(_db, _emailSender);
            checkExaminations = checkDate.Check(7);
            return View(checkExaminations);
        }

        [Authorize(Roles = "manager")]
        public IActionResult Reminder()
        {
            checkDate.SendAllEmail(checkExaminations);
            return View(checkExaminations);
        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="employee"></param>
        /// <returns></returns>
        [Authorize(Roles = "manager")]
        [HttpGet]
        public IActionResult NewExamination(Employee employee = null)
        {
            ViewModelAddExam viewModel = new ViewModelAddExam();

            var examinationProtocols = _db.ExaminationProtocols.ToList();
            int numProtocol = 0;

            if (examinationProtocols.Count != 0)
            {
                ExaminationProtocol examinationProtocol = examinationProtocols.OrderByDescending(x => x.num_protocol).First();
                examinationProtocol.num_protocol++;
                numProtocol = examinationProtocol.num_protocol;
            }
            else
            {
                numProtocol = 1;
            }

            viewModel.NumProtocol = numProtocol;


            if (employee.code != 0)
            {
                Person person = _db.Persons.Find(employee.Person.code);
                viewModel.IdPerson = person.code;

            }


            List<ExaminationReason> ExaminationReasons = _db.ExaminationReasons.ToList();
            IEnumerable<ExaminationReason> listExaminationReasons = (IEnumerable<ExaminationReason>)ExaminationReasons;
            ViewBag.selectExaminationReasons = new SelectList(listExaminationReasons, "code", "name");

            var commissions = _db.Commissions.ToList();
            List<Document> commands = new List<Document>();
            if (commissions.Count != 0)
            {
                
                foreach(Commission commission in commissions)
                {
                    Document docCommand = _db.Documents.Find(commission.doc);
                    commands.Add(docCommand);
                }
            }

            IEnumerable<Document> listCommissions = (IEnumerable<Document>)commands;
            ViewBag.selectCommissions = new SelectList(listCommissions, "code", "number_document");
           

            return View(viewModel);

        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="viewModel"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        [Authorize(Roles = "manager")]
        [HttpPost]
        public IActionResult NewExamination(ViewModelAddExam viewModel, [FromForm] IFormFile file)
        {
            
            Document document = new Document();


            if (file != null)
            {
                List<string> filesPath = new List<string>();

                long dateticks1 = DateTime.Now.Ticks;
                long datemilliseconds1 = dateticks1 / 10000;


                string fileName = String.Format(@"Content\Files\OT\{0}_{1}", datemilliseconds1, file.FileName);
                String savePath = Path.Combine(_env.WebRootPath, fileName);

                filesPath.Add(savePath);


                using (FileStream fileStream = new FileStream(savePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                //lololo


                /*
                Commission com = _db.Commissions.Where(x => x.doc == viewModel.Commission.code).First();

                List<MemberOfCommission> memes = _db.MemberOfCommissions.Where(x => x.code_commission == com.code).ToList();

                Employee employee = _db.Employees.Where(x => x.code_p000011 == viewModel.IdPerson).First();

                Person person = _db.Persons.Where(x => x.code == viewModel.IdPerson).First();

                ExaminationReason reason = _db.ExaminationReasons.Where(x => x.code == viewModel.Reason.code).First();
                */
                ProtocolWord pr = new ProtocolWord();
                pr.CreateProtocol();//viewModel, com, memes, person, reason

                //lololo
                /*
                 * Санёк зденсь генерирует файл ворд
                 * 
                 * 
                 * 
                 * 
                 * filesPath.Add(savePath2);
                 * */


                // Добавление архива с документами и сгенерированного файла протокола в архив


                string archivPath = String.Format(@"Content\Files\OT\Archiv");
                String rootArchivPath = Path.Combine(_env.WebRootPath, archivPath);

                string archivName = String.Format(@"{0}.{1}.{2}_{3}.zip", DateTime.Now.Day, DateTime.Now.Month, DateTime.Now.Year, datemilliseconds1);
                
                List<string> fileNames = new List<string>();
                fileNames.Add(String.Format(@"{0}_{1}", datemilliseconds1, file.FileName));


                long dateticks2 = DateTime.Now.Ticks;
                long datemilliseconds2 = dateticks2 / 10000;
                string fileName2 = String.Format(@"Content\Files\OT\{0}_{1}", datemilliseconds2, file.FileName);
                String savePath2 = Path.Combine(_env.WebRootPath, fileName);

                filesPath.Add(savePath2);


                fileNames.Add(String.Format(@"{0}_{1}", datemilliseconds2, file.FileName));

                Archivator.ZipArchive(rootArchivPath, archivName, filesPath, fileNames);

                String savePathArchiv = Path.Combine(rootArchivPath, archivName);


                document.link = savePathArchiv;
            }



            ExaminationProtocol protocol = new ExaminationProtocol();

            protocol.num_protocol = viewModel.NumProtocol;
            

            Examination examination = new Examination();
            examination.Employee =_db.Employees.Where(x => x.Person.code == viewModel.IdPerson).FirstOrDefault();

            int countYears = _db.ExaminationPeriods.Where(x => x.code_p000008 == examination.Employee.code_p000008).FirstOrDefault().count_years;

            protocol.DateProtocol = _db.Dates.Where(x => x.date == viewModel.DateProtocol).FirstOrDefault();

            DateTime dateNaxt = new DateTime(protocol.DateProtocol.date.Year + countYears, protocol.DateProtocol.date.Month, protocol.DateProtocol.date.Day);

            examination.DateNextCheck = _db.Dates.Where(x => x.date == dateNaxt).FirstOrDefault();


            document.Date = protocol.DateProtocol;
            protocol.DocumentProtocolArchiv = document;

            protocol.Examination = examination;

            protocol.CommandOfCommission = _db.Documents.Where(x => x.code == viewModel.Commission.code).FirstOrDefault();

            protocol.ExaminationReason = _db.ExaminationReasons.Where(x => x.code == viewModel.Reason.code).FirstOrDefault();

            protocol.result = viewModel.Result;
            
            protocol.notice = viewModel.Notice;

            

            _db.ExaminationProtocols.Add(protocol);
            _db.SaveChanges();

            

            
            return PartialView("_NewExaminationMessage", dateNaxt.ToShortDateString());
        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="searchText"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult NewExaminationPartial(string searchText)
        {
            searchText = searchText.ToUpper();

            List<Person> foundPeople = new List<Person>();

            List<Person> people = _db.Persons.ToList();

            string buffer;

            foreach(Person person in people)
            {
                buffer = (person.last_name + person.first_name + person.father_name).ToUpper();

                if(buffer.IndexOf(searchText) > -1 && person.Employee != null)
                {
                    foundPeople.Add(person);
                }
            }


            return PartialView("_NewExaminationPartial", foundPeople);
        }


    }
}

bes/1/allservices/AllServices/Views/OT/AllExaminations.cshtml
@model IEnumerable<ModelsLibrary.Models.Examination>

@{
    ViewData["Title"] = "Список проверок знаний";
}

<div class="concat-block">
    <h2 class="h2">@ViewData["Title"]</h2>
    <hr />
    <div class="table-block">
        <div class="table-line">
            <div class="table-item">ФИО</div>
            <div class="table-item">Табельный №</div>
            <div class="table-item">Организация</div>
            <div class="table-item">Подразделение</div>
            <div class="table-item">Дата следующей проверки</div>
            <div class="table-item">Документ</div>
            <div class="table-item">Тип проверки</div>
            <div class="table-item">Примечания</div>
            <div class="table-item">Причина</div>
            <div class="table-item">Действия</div>
        </div>
        @foreach (var item in Model)
        {
            <div class="table-line">
                <div class="table-item">@item.Employee.Person.first_name @item.Employee.Person.last_name @item.Employee.Person.father_name</div>
                <div class="table-item">@item.Employee.num_tab</div>
                <div class="table-item">@item.Employee.Department.Organization.abbreviation</div>
                <div class="table-item">@item.Employee.Department.name</div>
                <div class="table-item">@item.DateNextCheck.date.ToShortDateString()</div>

                <div class="table-item">
                    @Html.ActionLink("Изменить", "", new { id = item.code }) |
                    @Html.ActionLink("Удалить", "", new { id = item.code }, new { @class = "del", @onclick = "return confirmDelete();" })
                </div>
            </div>
        }
    </div>
    <div class="button-add" onmouseover="hover();" onmouseout="out();"><a id="add-link" href="AddExamination">Добавить</a></div>
</div>

@section Scripts {
    @if (ViewBag.Message != null)
    {
        <script>
            alert("@Html.Raw(ViewBag.Message)");
        </script>
    }
}

bes/1/allservices/AllServices/Views/OT/CheckExaminations.cshtml
@model List<ModelsLibrary.Models.Examination>

@{
    ViewData["Title"] = "CheckExaminations";
}

<div class="concat-block">
    <h2 class="h2">@ViewData["Title"]</h2>
    <hr />
    <div class="table-block">
        <div class="table-line">
            <div class="table-item">ФИО</div>
            <div class="table-item">Табельный №</div>
            <div class="table-item">Организация</div>
            <div class="table-item">Подразделение</div>
            <div class="table-item">Дата следующей проверки</div>
            <div class="table-item">Документ</div>
            <div class="table-item">Тип проверки</div>
            <div class="table-item">Примечания</div>
            <div class="table-item">Причина</div>
            <div class="table-item">Действия</div>
        </div>
        @foreach (var item in Model)
        {
            <div class="table-line">
                <div class="table-item">@item.Employee.Person.last_name @item.Employee.Person.first_name @item.Employee.Person.father_name</div>
                <div class="table-item">@item.Employee.num_tab</div>
                <div class="table-item">@item.Employee.Department.Organization.abbreviation</div>
                <div class="table-item">@item.Employee.Department.name</div>
                <div class="table-item">@item.DateNextCheck.date.ToShortDateString()</div>

                <div class="table-item">
                    @Html.ActionLink("Изменить", "", new { id = item.code }) |
                    @Html.ActionLink("Удалить", "", new { id = item.code }, new { @class = "del", @onclick = "return confirmDelete();" })
                </div>
            </div>
        }
    </div>
    <div class="button-add" onmouseover="hover();" onmouseout="out();"><a id="add-link" href="AddExamination">Добавить</a></div>
    <a class="link" asp-controller="OT" asp-action="Reminder">Напомнить</a>
</div>

@section Scripts {
    @if (ViewBag.Message != null)
    {
        <script>
            alert("@Html.Raw(ViewBag.Message)");
        </script>
    }
}

bes/1/allservices/AllServices/Views/OT/Index.cshtml
@{
    ViewData["Title"] = "Справочники";
}
    <div>
        <div class="button-directory" onclick="show();">Справочники</div>
        <div class="button-directory">
            <a href="/TrainingTB">Обучение</a>
        </div>

        @if (User.IsInRole("ot manager") || User.IsInRole("admin"))
        {
            <a class="link" asp-controller="OT" asp-action="NewExamination">Проверка знаний</a>
        }

    </div>

<div id="directoryes" class="directoryes-block">
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllGenders">Половая принадлежность</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllAbsenceReasons">Причины отсутствия</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllInstitutions">Учреждения образования</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllMedRequirements">Медицинские требования</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllEducationTypes">Образования</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllEducationQualifications">Квалификация</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllExaminationReasons">Причина проверки знаний</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllRelationshipDegrees">Степень родства</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllTemplateForWorks">Шаблон приема на работу</a>
    </div>
    <div class="directory-item">
        <a class="link" asp-controller="Directory" asp-action="AllHarms">Вредные и опасные условия труда</a>
    </div>
</div>

bes/1/allservices/AllServices/Views/OT/NewExamination.cshtml
@using ModelsLibrary.Models
@model AllServices.Models.OT.ViewModelAddExam

@{    
    ViewData["Title"] = "Проверка знаний";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form asp-action="NewExaminationPartial" asp-controller="OT" enctype="multipart/form-data" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#result">
        <label>Найти сотрудника </label>
        <input type="text" id="searchText" name="searchText" onkeyup="searchEmployee(this.id);" />
        <input type="submit" id="send" class="hide"/>
    </form>
<div id="result"></div>

        <form asp-action="NewExamination" asp-controller="OT" enctype="multipart/form-data">

            <div>
                <label asp-for="NumProtocol"></label>
                <label>@Model.NumProtocol</label>
                <input asp-for="NumProtocol" type="hidden" />
            </div>

            <div>
                <label asp-for="DateProtocol"></label>
                <input type="date" asp-for="DateProtocol" value="" />

            </div>

            <div>
                <label asp-for="Commission"></label>
                <select class="ViewBag" asp-for="@Model.Commission.code" asp-items="ViewBag.selectCommissions"></select>

            </div>


            <div id="person">
                <label asp-for="IdPerson"></label>
                <label id="idPer"></label>
                <input type="hidden" asp-for="IdPerson" />

            </div>


            <div>
                <label asp-for="Reason"></label>

                <select class="ViewBag" asp-for="@Model.Reason.code" asp-items="ViewBag.selectExaminationReasons"></select>

            </div>


            <div>
                <label asp-for="Result"></label>
                <select asp-for="Result">
                    <option value="true">Прошёл</option>
                    <option value="false" selected>Не прошёл</option>
                </select>

            </div>

            <div>
                <label asp-for="Notice"></label>
                <textarea asp-for="Notice"></textarea>

            </div>

            <div>

                <label for="Upload"><span>Прикрепить архив с документами</span></label>
                <input type="file" id="file" name="file" />

            </div>

            <div>
                <input type="submit" value="Сохранить" />
            </div>


        </form>


<script type="text/javascript">

    function searchEmployee(id) {

        var text = String(document.getElementById(id).value);

        if (text.length > 1) {
            document.getElementById("send").click();

        }
    }

    function addToForm(id) {
        document.getElementById("idPer").innerText = document.getElementById(id).innerText;
        document.getElementById("IdPerson").value = id;
    }


</script>

bes/1/allservices/AllServices/Views/OT/_NewExaminationMessage.cshtml
@model string
@{
    ViewBag.Title = "Проверка знаний добавлена";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    alert('Информация о проверке знаний успешно добавлена! Примерная дата следующей проверки знаний @Model');
    location.href = '@Url.Action("Index", "OT")';

</script>

bes/1/allservices/AllServices/Views/OT/_NewExaminationPartial.cshtml
@using ModelsLibrary.Models;
@model List<ModelsLibrary.Models.Person>

@for (int i = 0; i < Model.Count; i++)
{
    string text = String.Format("{0} {1} {2} - {3}", Model[i].last_name,Model[i].first_name, Model[i].father_name, Model[i].Employee.SpecialtyEmployee.name);

    <label for="@Model[i].code" id="@Model[i].code" onclick="addToForm(this.id);">@text</label><br />
}