bes/2/rupbes.by/rupbes/Controllers/DirectoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rupbes.Models.DatabaseBes;

namespace rupbes.Controllers
{
    [Filters.Culture]
    public class DirectoryController : Controller
    {
        private Database db = new Database();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Companies = db.Companies.Where(x => (x.Id >= 9) && (x.Id <= 17)).ToList();
            return View();
        }

        [HttpPost]
        public ActionResult SearchName(string searchStr)
        {

            List<Employee> employees = db.Employees.Where(x =>String.Concat(
                x.Person.LastName, " ", x.Person.FirstName, " ", x.Person.FatherName, " ",
                x.Person.FirstName, " ", x.Person.LastName, " ", x.Person.FatherName, " ",
                x.Person.LastName, " ", x.Person.FatherName, " ", x.Person.FirstName, " ",
                x.Person.FirstName, " ", x.Person.FatherName, " ", x.Person.LastName, " ",
                x.Person.FatherName, " ", x.Person.LastName, " ", x.Person.FirstName, " ",
                x.Person.FatherName, " ", x.Person.FirstName, " ", x.Person.LastName)
                .Contains(searchStr)).ToList();

            if (employees.Count > 0)
            {
                return PartialView("_SearchName", employees);
            }
            else
            {
                string result = "По вашему запросу ничего не найдено";
                return PartialView("_SearchEmpty", result);
            }
        }

        [HttpPost]
        public ActionResult SelectCompany(int companyId)
        {
            ViewBag.Departments = db.Departments.Where(x => x.CompanId == companyId);
            Company company = db.Companies.Find(companyId);
            return PartialView("_SelectCompany",company);
        }
        [HttpPost]
        public ActionResult SelectDepartment(int depId)
        {
            List<Employee> employees = db.Employees.Where(x => x.DepartmentId == depId).ToList();
            ViewBag.Department = db.Departments.Find(depId);
            return PartialView("_SelectDepartment", employees);
        }
    }
}

bes/2/rupbes.by/rupbes/Views/Directory/Index.cshtml
@{
    ViewBag.Title = Resources.Resource.EmailDirectory;
}

<h2 class="headline">@Resources.Resource.EmailDirectory</h2>
<section class="form-block">
    <form>
        <div class="dir-label">
            <input id="searchForm" type="text" placeholder="@Resources.Resource.DirSearchPlaceholder" />
        </div>
    </form>
    <div class="one-window-link centered">
        <button id="advSearchBtn">@Resources.Resource.DirAdvSearch</button>
    </div>
</section>
<section class="content">
    <div id="advSearchForm" class="dir-adv-search-form" style="display:none;">
        <div class="dir-label">
            <select id="selCompany"class="select dir-select">
                <option>@Resources.Resource.DirChooseFil</option>
                @foreach (rupbes.Models.DatabaseBes.Company company in ViewBag.Companies)
                {
                    <option value="@company.Id">@company.Abbreviation</option>
                }
            </select>
        </div>
        <div id="selDepBlock" class="dir-label"></div>
    </div>
    <div id="searchResult"></div>
</section>
@section scripts {
    <script>
        var searchResult = $("#searchResult");
        var advSearchBtn = document.getElementById('advSearchBtn');
        var searchForm = $("#searchForm");
        var searchFormJS = document.getElementById('searchForm');
        var advSearchForm = document.getElementById('advSearchForm');
        var selCompany = $("#selCompany");
        var selDepBlock = $("#selDepBlock");
        var selDepartment = $('#selDepartment');

        var check_ready = 1;
        var queue = 0;
        var req_stack = new Array();

        searchFormJS.oninput = function () {
            searchName(searchFormJS.value);
        }

        function searchName(searchStr) {
            advSearchForm.style.display = 'none';
            if (searchStr.length > 2) {
                if (queue == 0) {
                    req_stack.push(searchStr);
                }
                else if (queue == 1) {
                    req_stack.unshift(searchStr);
                    queue = 0;
                }
                if (check_ready == 1) {
                    
                    while (req_stack.length > 1) {
                        req_stack.shift();
                    }
                    let str = req_stack.shift();
                    check_ready = 0;
                    $.ajax({
                        type: "post",
                        url: '@Url.Action("SearchName","Directory")',
                        data: { 'searchStr': str },
                        success: function (data) {
                            searchResult.html(data);
                            check_ready = 1;
                            if (req_stack.length != 0) {
                                queue = 1;
                                searchName(req_stack.shift());
                            }
                        }
                    })
                }
                
            }
            else {
                searchResult.empty();
            }
        }

        selCompany.bind("change", function () {
            searchResult.empty();
            $.ajax({
                    type: "post",
                    url: '@Url.Action("SelectCompany","Directory")',
                    data: { 'companyId': this.value },
                        success: function (data) {
                            selDepBlock.html(data);
                        }
            })
            
        });
        advSearchBtn.onclick = function(e) {
            e.preventDefault();
            document.getElementById('searchForm').value = '';
            searchResult.empty();            
            if (advSearchForm.style.display == 'none') {
                advSearchForm.style.display = 'block';
            }
            else if (advSearchForm.style.display == 'block') {
                advSearchForm.style.display = 'none';
            }
            
        }
    </script>

}

bes/2/rupbes.by/rupbes/Views/Directory/_SearchEmpty.cshtml
<p>@Model</p>

bes/2/rupbes.by/rupbes/Views/Directory/_SearchName.cshtml
<table class="dir-table">
    <tr class="dir-table-row">
        <th class="dir-table-cell">@Resources.Resource.ContactsName</th>
        <th class="dir-table-cell">@Resources.Resource.ContactsPost</th>
        <th class="dir-table-cell">@Resources.Resource.ContactsPhone</th>
        <th class="dir-table-cell">Email</th>
    </tr>
    @foreach (rupbes.Models.DatabaseBes.Employee employee in Model)
    {
    <tr class="dir-table-row">
        <td class="dir-table-cell">
            @employee.Person.LastName @employee.Person.FirstName @employee.Person.FatherName
        </td>
        <td class="dir-table-cell">
            @employee.Post.Name
        </td>
        <td class="dir-table-cell">
            @{
                if (employee.Contacts.Any(x => x.ContactsTypeId == 2))
                {
                    foreach (rupbes.Models.DatabaseBes.Contact contact in employee.Contacts.Where(x => x.ContactsTypeId == 2))
                    {
                        <a href="tel:@contact.ContactName"> @contact.ContactName</a>
                    }
                }
                else
                {
                    <span>-</span>
                }
            }
        </td>
        <td class="dir-table-cell">
            @foreach (rupbes.Models.DatabaseBes.Contact contact in employee.Contacts.Where(x => x.ContactsTypeId == 1))
            {
            <a href="mailto:@contact.ContactName"> @Html.Raw(contact.ContactName.Replace("@", "<wbr>@"))</a>
            }
        </td>
    </tr>
    }
</table>

bes/2/rupbes.by/rupbes/Views/Directory/_SelectCompany.cshtml
<p>
    @Model.Abbreviation -
    @foreach (rupbes.Models.DatabaseBes.Contact contact in Model.Contacts)
    {
    <span><a href="mailto:@contact.ContactName">@contact.ContactName</a> </span>
    }
</p>
<select id="selDepartment" class="select dir-select">
    <option>@Resources.Resource.DirChooseDep</option>
    @foreach (rupbes.Models.DatabaseBes.Department dep in ViewBag.Departments)
    {
        <option value="@dep.Id">@dep.Name</option>
    }
</select>
<script>
        var searchResult = $("#searchResult");
        var selDepartment = $('#selDepartment');

        selDepartment.bind("change", function () {
            $.ajax({
                type: "post",
                url: '@Url.Action("SelectDepartment","Directory")',
                data: { 'depId': this.value },
                success: function (data) {
                    searchResult.html(data);
                }
            })
        });
</script>

bes/2/rupbes.by/rupbes/Views/Directory/_SelectDepartment.cshtml
@model List<rupbes.Models.DatabaseBes.Employee>
@if (ViewBag.Department.Contacts.Count > 0)
{
<div class="dir-label">
    @ViewBag.Department.Name
    @foreach (rupbes.Models.DatabaseBes.Contact contact in ViewBag.Department.Contacts)
    {
        <span><a href="mailto:@contact.ContactName">@contact.ContactName </a> </span>
    }
</div>
}
@if (Model.Any())
{
 <table class="dir-table">
     <tr class="dir-table-row">
         <th class="dir-table-cell">@Resources.Resource.ContactsName</th>
         <th class="dir-table-cell">@Resources.Resource.ContactsPost</th>
         <th class="dir-table-cell">@Resources.Resource.ContactsPhone</th>
         <th class="dir-table-cell">Email</th>
     </tr>
    @foreach (rupbes.Models.DatabaseBes.Employee employee in Model)
    {
     <tr class="dir-table-row">
         <td class="dir-table-cell">
             @employee.Person.LastName @employee.Person.FirstName @employee.Person.FatherName
         </td>
         <td class="dir-table-cell">
             @employee.Post.Name
         </td>
         <td class="dir-table-cell">
             @{ 
                 if (employee.Contacts.Any(x => x.ContactsTypeId == 2))
                 {
                     foreach (rupbes.Models.DatabaseBes.Contact contact in employee.Contacts.Where(x => x.ContactsTypeId == 2))
                     {
                     <a href="tel:@contact.ContactName"> @contact.ContactName</a>
                     }
                 }
                 else
                 {
                     <span>-</span>
                 }
              }
         </td>
         <td class="dir-table-cell">
             @foreach (rupbes.Models.DatabaseBes.Contact contact in employee.Contacts.Where(x => x.ContactsTypeId == 1))
             {
                 <a href="mailto:@contact.ContactName"> @Html.Raw(contact.ContactName.Replace("@", "<wbr>@"))</a>
             }
         </td>
     </tr>
     }
</table>
}